import express from 'express';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import studentRoutes from './studentRoutes.js';
import courseRoutes from './courseRoutes.js';
import subjectRoutes from './subjectRoutes.js';
import assignmentRoutes from './assignmentRoutes.js';
import teacherRoutes from './teacherRoutes.js';
import gradeRoutes from './gradeRoutes.js';
import attendanceRoutes from './attendanceRoutes.js';
import paymentRoutes from './paymentRoutes.js';
import periodRoutes from './periodRoutes.js';
import subPeriodRoutes from './subPeriodRoutes.js';
import insumoRoutes from './insumoRoutes.js';
import reportRoutes from './reportRoutes.js';
import reportCardRoutes from './reportCardRoutes.js';
import institutionRoutes from './institutionRoutes.js';
import schoolYearRoutes from './schoolYearRoutes.js';
import scheduleRoutes from './scheduleRoutes.js';
import gradeScaleRoutes from './gradeScaleRoutes.js';
import studentProfileRoutes from './studentProfileRoutes.js';
import supplementaryRoutes from './supplementaryRoutes.js';
import promotionRoutes from './promotionRoutes.js';
import backupRoutes from './backupRoutes.js';
import resetRoutes from './resetRoutes.js';
import representanteRoutes from './representanteRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import tareaEntregaRoutes from './tareaEntregaRoutes.js';
import permissionRoutes from './permissionRoutes.js';
import logRoutes from './logRoutes.js';
import settingsRoutes from './settingsRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import emailConfigRoutes from './emailConfigRoutes.js';
import mensajeRoutes from './mensajeRoutes.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/users', userRoutes);
router.use('/students', studentRoutes);
router.use('/courses', courseRoutes);
router.use('/subjects', subjectRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/teachers', teacherRoutes);
router.use('/grades', gradeRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/payments', paymentRoutes);
router.use('/periods', periodRoutes);
router.use('/sub-periods', subPeriodRoutes);
router.use('/insumos', insumoRoutes);
router.use('/reports', reportRoutes);
router.use('/report-cards', reportCardRoutes);
router.use('/institutions', institutionRoutes);
router.use('/school-years', schoolYearRoutes);
router.use('/schedules', scheduleRoutes);
router.use('/grade-scales', gradeScaleRoutes);
router.use('/student-profile', studentProfileRoutes);
router.use('/supplementary', supplementaryRoutes);
router.use('/promotion', promotionRoutes);
router.use('/backup', backupRoutes);
router.use('/reset', resetRoutes);
router.use('/representantes', representanteRoutes);
router.use('/notifications', notificationRoutes);
router.use('/tareas', tareaEntregaRoutes);
router.use('/', permissionRoutes);
router.use('/logs', logRoutes);
router.use('/settings', settingsRoutes);
router.use('/email-config', emailConfigRoutes);
router.use('/mensajes', mensajeRoutes);

export default router;

